### ISSUE TITLE
下发短信后会 print_r 出响应对象

### ISSUE THREAD

**Issue by BruceFan-FS71** [HyanCat/aliyun-sms-php#1]
在实例化 SmsService 对象后，调用 send 方法，会 print_r 出响应对象。这样会影响后续的处理，例如：返回 JSON 对象。

稍后会提交一个 pull，请留意。

**Comment by HyanCat** [comment]
感谢反馈，这个短信包以后不维护了，建议考虑使用 https://github.com/HyanCat/short-messenger 替代。支持阿里云和 SendCloud，有更好的扩展性。 也是我目前在用的。
